### ISSUE TITLE
Add tickbox or button to load generated RunDataLibrary into the active matlab workspace.

### ISSUE THREAD

**Issue by jpagett** [weldlabucsb/dataManager#8]
This can pretty easily be done if GetRunData is updated to also output the RunDataLibrary itself. Then we'd just need to assign the output of GetRunData like this
```matlab
[~,Data] = GetRunData(...)
```
and add a line following it like this to write it to the current workspace
```matlab
assignin('base', 'Data', Data)
```

**Comment by jpagett** [comment]
I'll do this once the most recent pull is approved

**Comment by mlprichard** [comment]
Done. I deleted the branch though. Do you want to restore it or just commit to master?

**Comment by jpagett** [comment]
Deleting branch is good! Thanks.

________________________________

**Comment by jpagett** [comment]
Matlab automatically opens the generated RunDataLibrary without this fix. Cause unknown, but this is desired behavior. Closed until it becomes a problem.
